# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-06 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Item',
        ),
    ]
